language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
- stable
install:
  - npm install
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g coveralls
script: 
  - npm test
after_script:
  - npm run coveralls
services:
  - redis-server